# Generated by Django 5.0.6 on 2024-08-17 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 8, 17, 20, 18, 33, 135762, tzinfo=datetime.timezone.utc)),
        ),
    ]
