# Generated by Django 5.0.6 on 2024-08-17 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_likepost_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 8, 18, 1, 0, 13, 601683)),
        ),
    ]
